### ISSUE TITLE
MUGEN is properly launched, but the bot hangs with a status of 0.

### ISSUE THREAD

**Issue by princessGasmask** [otaniemi-triforce/M.A.T.C.H.#3]
MUGEN is properly launched and the characters are scanned, but the bot hangs with a status of 0 after sending the "Miyako here-...Dan-kun wanted me to run some matches, so..." message in Discord. My [Title Info] within system.def is formatted as :

menu.itemname.watch = "WATCH"
menu.itemname.arcade = ""
menu.itemname.versus = ""
menu.itemname.teamarcade = ""
menu.itemname.teamversus = ""
menu.itemname.teamcoop = ""
menu.itemname.survival = ""
menu.itemname.survivalcoop = ""
menu.itemname.training = ""
menu.itemname.options = "OPTION"
menu.itemname.exit = ""

EDIT: Just to clarify, the input defined in config does match my in-game keybinds for player 2, yet after the game is launched the bot makes no inputs.

**Comment by Yarb** [comment]
This, I believe is due to bad documentation on how to actually use the system. Our bad as the system has been mainly in use by our team and the biggest issue has been getting the system running in the first place. Thus no-one has bothered to complete the documentation...until now.

The documentation is now updated to better describe how to actually use the system once it is running. Hopefully this will completely solve this issue.

**Comment by princessGasmask** [comment]
Perfect! Got this fixed and everything is running. I have one final issue that's not even major and it may be a general MUGEN inexperience issue, but I'll try my luck and see if we can get it solved.
